version: '3.8'
services:
  mongoDB1:
    image: mongo:6.0
    restart: always
    container_name: mongoDB1
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: component-2-1:latest
    container_name: component-2-1
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongoDB1:27017/db
      - SPRING_GRAPHQL_SCHEMA_LOCATION=classpath:/graphql/
    depends_on:
      - mongoDB1

volumes:
  mongo_data:
